apiVersion: v1
kind: Service
metadata:
  name: entra-agent
  labels:
    app.kubernetes.io/name: entra-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: entra-agent
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
