apiVersion: v1
kind: ServiceAccount
metadata:
  name: entra-agent
  labels:
    app.kubernetes.io/name: entra-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false
